---
title: "AnalyzingSocialGraphs"
author: "Steve Newns"
date: "December 9, 2017"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(magrittr)
```

# Social Network Analysis
Social networks are everywhere. According to Wikipedia, there are over 200 active social networking websites on the Internet, excluding dating sites. According to Google Trends, there has been a steady + constant rise in global interest in “social networks” since 2005. This is perfectly reasonable: the desire for social interaction is a fundamental part of human nature, + it should come as no surprise that this innate social nature would manifest in our technologies. But the mapping + modeling of social networks is by no means news.

In the mathematics community, an example of social network analysis at work = the calculation of a person’s **Erdős number**, which measures her distance from the prolific mathematician Paul Erdős. Erdős was arguably the most prolific mathematician of the 20th century + published over 1,500 papers during his career. Many of these papers were coauthored, + Erdős #'s measure a mathematician’s distance from the circle of coauthors Erdős enlisted. If a mathematician coauthored w/ Erdős on a paper, she'd have an Erdős # = 1, i.e., her distance to Erdős in the network of 20th-century mathematics = 1. If another author collaborated w/ 1 of Erdős’ coauthors but not w/ Erdős directly, that author has an Erdős # = 2, + so on. This metric has been used, though rarely seriously, as a crude measure of a person’s prominence in mathematics. Erdős #'s allow us to quickly summarize the massive network of mathematicians orbiting around Paul Erdős.

Erving Goffman, one of the most celebrated intellectuals of the 20th century + very much the equivalent of Paul Erdős in the social sciences based on the overwhelming breadth of his contributions, provides one of the best statements on the nature of human interaction: "When persons are present to one another they can function not merely as physical instruments but also as communicative ones. This possibility, no less than the physical one, is fateful for everyone concerned + in every society appears to come under strict normative regulation, giving rise to a kind of communication traffic order." — Erving Goffman, from *Behavior in public places: notes on the social organization of gatherings (1966)*

The “traffic order” Goffman was referring to is exactly a social network. The by-product of our desire to interact + socialize w/ each other are highly structured graphs, which provide a sort of “map” of our identities + histories. Social networking services such as Facebook, Twitter, + LinkedIn simply provide highly stylized templates for engaging in this very natural behavior. The innovation of these services is not in their function, but rather the way in which they provide insight into the social cartography of a very large portion of humanity. To hackers like us, data social networking sites expose is a veritable geyser of awesome. But the value of social graphs goes beyond social networking sites. 

There are several types of relationships that can be modeled as a network, + many of those are also
captured by various Internet services. Could map the relationships among movie watchers based on movies they watched on Netflix or show how various music genres relate to one another based on patterns of listeners using services such as Last.fm or Spotify. In a more basic way, we may also model the structure of a local CPU network—or even the entire Internet—as a massive series of **nodes** + **edges**. Although the study of social networks is very popular now, in large part due to the proliferation of social networking sites, what’s commonly referred to as “social network analysis” is a set of tools used + developed over the past several decades. 

At its core, the study of networks relies on the language of **graph theory** to describe interconnected objects. As early as 1736, Leonhard Euler used the concept of nodes + edges to formalize the Königsberg Bridge problem, an early variant of the Traveling Salesman Problem, in which you must devise a path through the city of Königsberg, Prussia (now Kaliningrad, Russia) by traversing each of its 7 bridges exactly once. Euler solved the problem by converting a map of the city to a simple graph w/ 4 nodes (city sections) + 7 edges (the bridges). In the 1920s, famed psychologist Jacob L. Moreno developed a method for studying human relationships called “sociometry.” Moreno was interested in how people’s social interactions affected their well-being, so he asked people who their friends were + began mapping this structure. In 1937, anthropologist Joan Criswell used Moreno’s sociometric methods to study racial cleavages between black + white elementary school children. Most of what we consider "contemporary" social network analysis is a conglomeration of theory + methods from a wide array of disciplines. A large portion comes from sociology, including prominent scholars such as Linton Freeman, Harrison White, Mark Granovetter, + many others. Likewise, many contributions have also come from physics, economics, CPU science, political science, psychology, + countless other disciplines + scholars. There are far too many authors + citations to list here, + tomes have been written that review the methods in this large area of study. Some of the most comprehensive include *Social Network Analysis*, by Stanley Wasserman + Katherine Faust, *Social + Economic Networks*, by Matthew O. Jackson, + *Networks, Crowds, + Markets* by David Easley + Jon Kleinberg 

**Case study** = entire data-hacking cycle of acquiring social network data, cleaning + structuring it, + finally analyzing it via the preeminent “open” social network of the day: Twitter, which is not really open in the sense that we can freely access all of its data, but like many social networking sites, it has an API w/ a strict rate limit We'll build a system for extracting data from Twitter w/out running into this rate limit + w/out violating Twitter’s TOS. In fact, we won’t ever access Twitter’s API directly.

Our project begins by building a local network, or **ego-network**, + snowballing from there in the same way that an Erdős # is calculated. 1st analysis = explore methods of community detection that attempt to partition social networks into cohesive subgroups. W/in the context of Twitter, this can give us info about the different social groups that a given user belongs to. Then we'll build our own “who to follow” recommendation engine using the structure of Twitter’s social graph.

An **ego-network** always refers to the structure of a social graph immediately surrounding a single **node** in a network. Specifically, it is the *subset* of a network induced by a **seed** (or **ego**) + its **neighbors** (those nodes directly connected to the seed). Put another way, the ego-network for a given node includes that node’s neighbors, the connections between the seed + those neighbors, + the *connections among the neighbors*.

# Thinking Graphically

Before we can dive head first into hacking the Twitter social graph, it will be useful to take a step back + define a **network**. Mathematically, a **network** (or **graph**) = simply a set of nodes + edges. These sets have no context + only serve the purpose of representing some world in which the edges connect the nodes to one another. In the most abstract formulation, these edges contain no info other than the fact that they connect 2 nodes. We can, however, see how this general vessel of organizing
data can quickly become more complex. 

**undirected graph** = edges of a graph have no direction = a connection between nodes in this case implies *mutuality of the tie*. For example, Dick + Harry share a connection, + b/c the graph is undirected, we can think of this as meaning they can exchange info, goods, etc. w/ one another over this tie. Also, b/c this is a very basic network setup, it is easy to overlook the fact that even in the undirected case, we have increased the complexity of the graph beyond the most general case we mentioned earlier = added labels to nodes, which is additional info, which is quite useful here, but is important to consider when thinking about how we move from a network abstraction to one that describes real data.

**directed graph** = edges have arrows that denote directionality of an edge. Now, the edges are *not* mutual, but indicate instead a one-way tie. For example, Dick + Drew have ties to John, but John only has a tie to Harry. Can then add **edge labels** to the graph (ex: positive or negative sign to each label), which could indicate a “like” or “dislike” relationship among the members of the network or some level of access. Just as node labels add info + context to a network, so too do edge labels. These labels can also be much more complex than a simple binary relationship. These labels could be weights indicating the strength ortype of a relationship.

It is important to consider the differences among these different graph types b/c social graph data encountered online comes in many different forms. Variation in how graphs are structured can affect how people use the service +, consequently, how we might analyze the data. Consider 2 popular social networking sites that vary in the class of graphs they use: Facebook + Twitter. FB = a massive, *undirected* social graph. B/c “friending” requires approval, all edges imply a mutual friendship. This has caused FB to evolve as a relatively more closed network w/ dense local network structures rather than the massive central hubs of a more open service. Twitter is a very large directed graph. The "following" dynamics on Twitter do not require mutuality, + therefore the service allows for large asymmetries in the directed graph in which celebrities, news outlets, + other high-profile users acts as major broadcast points for tweets. Although the differences in how connections are made between the services may seem subtle, the resulting differences are very large. By changing the dynamic slightly, Twitter has created an entirely different kind of social graph + one people use in a very different way than they use FB. Of course, the reasons for this difference go beyond the graph structures, including Twitter’s 140-character limit + the completely public nature of most Twitter accounts, but the graph structure powerfully affects how the entire network operates. We focus on Twitter + will therefore have to consider its directed graph structures during all aspects of the analysis. We begin with the challenge of collecting Twitter’s relationship data w/out exceeding the API rate limit or violating the TOS.